---
title: "Ion concentrations in Bisley, Puerto Rico streams before and after Hurricane Hugo"
format: html
---
## Background
This analysis sources and analyzes data from stream sites in Bisley Puerto Rico to replicate figure 3 in Schaefer et al. ([2000](https://doi.org/10.1017/s0266467400001358)).

## Data
The data were retrieved from the [Environmental Data Initiative](https://doi.org/10.6073/PASTA/F31349BEBDC304F758718F4798D25458). 

## Methods
The moving average of each ion concentration was calculated for each site in Bisley, Puerto Rico at 9 week intervals.

## Results
```{r, include = FALSE}
library(tidyverse)
bisley_mov_ave_long <- read_csv("../output/bisley_mov_ave_long.csv")
```
```{r, echo = FALSE, warning = FALSE}
ggplot(
  data = bisley_mov_ave_long,
  mapping = aes(
    x = window_start,
    y = concentration,
    color = site_id,
  )
) +
  xlim(ymd("1988-01-01"), ymd("1994-06-01")) +
  geom_line() +
  facet_wrap(
    ~ion,
    scales = "free_y",
    ncol = 1,
    strip.position = "left",
    labeller = as_labeller(c(
      ca_mgl = "Ca mg l^-1",
      k_mgl = "K mg l^-1",
      mg_mgl = "Mg mg l^-1",
      nh4n_ugl = "NH_4-N ug l^-1",
      no3n_ugl = "NO_3-N ug l^-1"
    ))
  ) +
  labs(
    x = "Year",
    y = "Concentration",
    color = "Site ID",
    subtitle = "Concentrations in Bisley, Puerto Rico streams before and after Hurricane Hugo, 9-wk moving averages from 1988 through 1994.
    (a) calcium, (b) potassium, (c) magnesium, (d) nitrate-N and (e) ammonium-N. The vertical lines mark 
    the time of hurricane disturbance."
  ) +
  geom_vline(
    xintercept = ymd("1989-09-18"),
    linetype = "dashed"
  )
```
